{{- if default "" .Values.externalUrl }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        ## General GitLab Configs
        ##
        # This is a free-form env var that GitLab Omnibus uses to configure
        # everything. We're passing this in from a configmap and pulling some
        # of the values from the env vars defined below. This is done to
        # avoid leaving secrets visible in kubectl.
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: gitlab_omnibus_config
        - name: GITLAB_ROOT_PASSWORD
        {{- if default "" .Values.gitlabRootPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: gitlab-root-password
        {{ end }}
        - name: EXTERNAL_URL
          value: {{ default "" .Values.externalUrl | quote }}
        ## 
        ## DB configuration
        ## TODO: Add username@hostname for the username for Postgres on Azure
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.binding.secretName }}
              key: postgresqlServerFullyQualifiedDomainName
        - name: DB_DATABASELOGIN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.binding.secretName }}
              key: databaseLogin
        - name: DB_SERVERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.binding.secretName }}
              key: postgresqlServerName
        - name: DB_USER
          value: {{ "$DB_DATABASELOGIN@$DB_SERVERNAME" }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.binding.secretName }}
              key: databaseLoginPassword
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.binding.secretName }}
              key: postgresqldbName
        ##
        ## Redis configuration
        ##
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.binding.secretName }}
              key: hostname
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.binding.secretName }}
              key: primaryKey
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.binding.secretName }}
              key: port
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /help
            port: http
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 200
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /help
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: gitlab-etc
          mountPath: /etc/gitlab
        - name: gitlab-data
          mountPath: /gitlab-data
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: gitlab-etc
      {{- if .Values.persistence.gitlabEtc.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-etc
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-data
      {{- if .Values.persistence.gitlabData.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
{{ else }}
{{ end }}
