apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: {{ .Values.postgresql.instance.name }}
spec:
  serviceClassName: azure-postgresqldb
  planName: {{ .Values.postgresql.instance.planName }}
  parameters:
    resourceGroup: {{ .Values.postgresql.instance.params.resourceGroup }}
    location: {{ .Values.postgresql.instance.params.location }}
    postgresqlServerName: {{ .Values.postgresql.instance.params.serverName }}
    postgresqlServerParameters:
      properties:
        {{ toYaml .Values.postgresql.instance.params.serverParams.properties.adminLogin}}
      allowPostgresqlServerFirewallRules:
        {{ toYaml .Values.postgresql.instance.params.serverParams.firewallRules}}
    postgresqldbName: {{ .Values.postgresql.instance.params.dbName }}
