apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
metadata:
  name: jz-gitlab-redis-binding
  namespace: default
spec:
  instanceRef:
    name: jz-gitlab-redis-instance
  secretName: jz-gitlab-redis-secret
