apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: jz-gitlab-redis-instance
  namespace: default
spec:
  serviceClassName: azure-rediscache
  planName: basic
  parameters:
    resourceGroup: demo
    cacheName: jz-gitlab-redis # must be globally unique
    parameters:
      location: eastus
      enableNonSslPort: true
      sku:
        name: Basic
        family: C
        capacity: 0
