apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ template "fullname" . }}-mysql-instance
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  externalClusterServiceClassName: azure-mysqldb
  externalClusterServicePlanName: standard800
  parameters:
    location: eastus
    resourceGroup: {{ .Release.Namespace }}
    sslEnforcement: disabled
