apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: {{ template "fullname" . }}-mysql-instance
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceClassName: azure-mysqldb
  planName: standard800
  parameters:
    location: eastus
    resourceGroup: {{ .Release.Namespace }}
    sslEnforcement: disabled
